name: flower_giver
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.0

dependencies:
  dotenv: ^4.2.0
  google_generative_ai: ^0.4.6
  http: ^1.3.0
  meta: ^1.16.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
